
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const esc = s => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const KEY='csorro_studio_reviews_v55';
let selectedId=null; let filter='all';
function seed(){return [{id:'review-1',title:'Recording intro v2',project:'Ryan Recording Prep',type:'Video edit',status:'waiting_review',version:2,sizeMb:184,created:'Today 10:24',fileName:'intro-v2.mp4',preview:'',comments:[{at:'00:12',body:'Tighten the first cut before the logo sting.',status:'open'},{at:'01:04',body:'Audio ducking feels too heavy here.',status:'open'}]},{id:'review-2',title:'Thumbnail concept pack',project:'Ryan Recording Prep',type:'Thumbnail',status:'changes_requested',version:3,sizeMb:42,created:'Yesterday',fileName:'thumbnail-pack.png',preview:'',comments:[{at:'Design',body:'Use stronger subject separation and warmer contrast.',status:'open'}]},{id:'review-3',title:'Final sponsor read export',project:'Ryan Recording Prep',type:'Short clip',status:'approved',version:1,sizeMb:96,created:'Monday',fileName:'sponsor-read.mov',preview:'',comments:[{at:'Final',body:'Approved for upload.',status:'resolved'}]}]}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch{return seed()}}
function save(data){localStorage.setItem(KEY,JSON.stringify(data));}
let reviews=load();
function render(){const list=$('#studioReviewList'); if(!list)return; const visible=reviews.filter(r=>filter==='all'||r.status===filter); if(!visible.length){list.innerHTML='<div class="empty-studio-v55"><b>No reviews here yet.</b><p>Upload a clip/image or change the filter.</p></div>'}else{list.innerHTML=visible.map(r=>`<article class="studio-review-card-v55 ${r.id===selectedId?'active':''}" data-id="${esc(r.id)}"><div class="studio-thumb-v55">${r.preview? (r.previewType?.startsWith('image')?`<img src="${r.preview}"/>`:`<video src="${r.preview}" muted></video>`):'▶'}</div><div><h3>${esc(r.title)}</h3><p>${esc(r.project)} · ${esc(r.fileName||r.type)}</p><div class="studio-meta-v55"><span>v${r.version}</span><span>${esc(r.type)}</span><span>${r.sizeMb||0} MB</span><span>${(r.comments||[]).length} notes</span></div></div><span class="status-pill-v55 ${esc(r.status)}">${esc(r.status.replaceAll('_',' '))}</span></article>`).join('')}
list.querySelectorAll('[data-id]').forEach(card=>card.onclick=()=>{selectedId=card.dataset.id;render();renderInspector();}); renderStorage();}
function renderStorage(){const total=reviews.reduce((a,r)=>a+(+r.sizeMb||0),0); const limit=2048; $('#studioStorageText') && ($('#studioStorageText').textContent=`${total} MB used / ${limit} MB free test limit`); $('.storage-meter-v55')?.style.setProperty('--storage',Math.min(100,total/limit*100)+'%');}
function renderInspector(){const wrap=$('#studioInspector'); const r=reviews.find(x=>x.id===selectedId); if(!wrap||!r){return;} wrap.innerHTML=`<span class="mini-label blue">${esc(r.project)}</span><h2>${esc(r.title)}</h2><p class="muted">${esc(r.type)} · Version ${r.version} · ${esc(r.fileName||'No file name')}</p><div class="review-preview-v55">${r.preview? (r.previewType?.startsWith('image')?`<img src="${r.preview}"/>`:`<video src="${r.preview}" controls></video>`):'<span>Preview placeholder</span>'}</div><select id="reviewStatus"><option value="waiting_review">Waiting review</option><option value="changes_requested">Changes requested</option><option value="approved">Approved</option></select><div class="studio-action-row-v55"><button class="btn" id="saveStatus">Update status</button><button class="btn-secondary" id="newVersion">New version</button><button class="btn-secondary" id="shareReview">Share to chat</button><button class="btn-secondary danger" id="deleteReview">Delete</button></div><hr/><h3>Timestamped feedback</h3><input id="commentTime" placeholder="Timestamp e.g. 00:42 or Design"/><textarea id="commentBody" placeholder="Write feedback or approval note..."></textarea><button class="btn" id="addComment">Add comment</button><div class="comment-list-v55">${(r.comments||[]).map(c=>`<div class="comment-v55"><b>${esc(c.at)}</b><p>${esc(c.body)}</p><small>${esc(c.status||'open')}</small></div>`).join('')||'<p class="muted">No comments yet.</p>'}</div>`; $('#reviewStatus').value=r.status; $('#saveStatus').onclick=()=>{r.status=$('#reviewStatus').value;save(reviews);render();renderInspector();}; $('#newVersion').onclick=()=>{r.version++; r.status='waiting_review'; r.comments.unshift({at:'Version '+r.version,body:'New version uploaded for review.',status:'open'});save(reviews);render();renderInspector();}; $('#shareReview').onclick=()=>alert('Mini test: this will share the review into Project Chat once live project chat is connected.'); $('#deleteReview').onclick=()=>{if(confirm('Delete this review?')){reviews=reviews.filter(x=>x.id!==r.id);selectedId=null;save(reviews);render();$('#studioInspector').innerHTML='<span class="mini-label blue">Review Panel</span><h2>Select a review</h2><p class="muted">Open a review to manage comments, versions and approval.</p>';}}; $('#addComment').onclick=()=>{const at=$('#commentTime').value.trim()||'General'; const body=$('#commentBody').value.trim(); if(!body)return; r.comments.unshift({at,body,status:'open'});save(reviews);render();renderInspector();};}
$$('[data-studio-filter]').forEach(b=>b.onclick=()=>{$$('[data-studio-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.studioFilter;render();});
$('#studioFile')?.addEventListener('change',e=>{const f=e.target.files[0]; if(!f)return; $('#selectedFileName').textContent=f.name+' · '+Math.max(1,Math.round(f.size/1024/1024))+' MB';});
$('#createReview')?.addEventListener('click',()=>{const f=$('#studioFile')?.files?.[0]; const title=$('#studioTitle').value.trim() || (f?f.name:'Untitled review'); let preview='',previewType='',sizeMb=0,fileName='Manual review'; if(f){preview=URL.createObjectURL(f); previewType=f.type; sizeMb=Math.max(1,Math.round(f.size/1024/1024)); fileName=f.name;} const r={id:'review-'+Date.now(),title,project:$('#studioProject').value,type:$('#studioType').value,status:'waiting_review',version:1,sizeMb,created:new Date().toLocaleString(),fileName,preview,previewType,comments:[]}; reviews.unshift(r); selectedId=r.id; save(reviews); $('#studioTitle').value=''; $('#studioFile').value=''; $('#selectedFileName').textContent='No file selected'; render(); renderInspector();});
$('#copyReviewLink')?.addEventListener('click',()=>{navigator.clipboard?.writeText(location.origin+'/os/app/studio/?review='+(selectedId||'latest')); alert('Mini test review link copied.');});
render(); if(reviews[0]){selectedId=reviews[0].id;render();renderInspector();}
