(function(){
  const key='csorroProjectHub020';
  const defaultState={
    room:'open',
    rooms:{
      open:[{name:'CORE',text:'Welcome to the open project chat. Use this for visible team updates.',time:'09:00'},{name:'Cristian',text:'Artwork approval is the main blocker today.',time:'09:12'}],
      artwork:[{name:'CORE',text:'Private artwork room ready for owner/designer notes.',time:'09:05'}],
      recording:[{name:'CORE',text:'Private recording room ready for owner/Ryan prep.',time:'09:06'}]
    },
    notes:['Confirm thumbnail direction before recording.','Check Ryan recording questions and timings.','Add final assets to project folder.'],
    perms:{allowOpen:true,allowPrivate:false,allowBoard:true},
    board:null
  };
  let state=JSON.parse(localStorage.getItem(key)||'null')||defaultState;
  const save=()=>localStorage.setItem(key,JSON.stringify(state));
  document.querySelectorAll('.project-tabs button').forEach(btn=>btn.addEventListener('click',()=>show(btn.dataset.panel)));
  document.querySelectorAll('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>show(btn.dataset.jump)));
  function show(id){document.querySelectorAll('.project-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.project-panel').forEach(p=>p.classList.toggle('active',p.id===id));}
  ['allowOpen','allowPrivate','allowBoard'].forEach(id=>{const el=document.getElementById(id);if(el){el.checked=!!state.perms[id];el.addEventListener('change',()=>{state.perms[id]=el.checked;save();});}});
  const roomTitle=document.getElementById('roomTitle'), messages=document.getElementById('messages');
  function renderRooms(){document.querySelectorAll('.room').forEach(r=>{r.classList.toggle('active',r.dataset.room===state.room);r.onclick=()=>{state.room=r.dataset.room;save();renderRooms();renderMessages();};});}
  function renderMessages(){if(!messages)return; const names={open:'# Open Project Chat',artwork:'Private · Artwork',recording:'Private · Recording'}; roomTitle.textContent=names[state.room]||('Private · '+state.room); messages.innerHTML=(state.rooms[state.room]||[]).map((m,i)=>`<div class="message ${m.name==='You'?'me':''}"><b>${escapeHtml(m.name)}</b>${escapeHtml(m.text)}<small>${escapeHtml(m.time)}</small></div>`).join(''); messages.scrollTop=messages.scrollHeight;}
  const chatForm=document.getElementById('chatForm'); if(chatForm)chatForm.addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('chatInput');const text=input.value.trim();if(!text)return;(state.rooms[state.room]||(state.rooms[state.room]=[])).push({name:'You',text,time:new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})});input.value='';save();renderMessages();});
  const addRoom=document.getElementById('addRoom'); if(addRoom)addRoom.onclick=()=>{const input=document.getElementById('roomName');const name=input.value.trim();if(!name)return;const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); if(!state.rooms[id]) state.rooms[id]=[{name:'CORE',text:'Private room created: '+name,time:new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}]; const b=document.createElement('button');b.className='room';b.dataset.room=id;b.innerHTML='Private · '+escapeHtml(name)+' <small>Custom room</small>';document.querySelector('.new-room').before(b);input.value='';state.room=id;save();renderRooms();renderMessages();};
  function renderNotes(){const board=document.getElementById('stickyBoard'); if(!board)return; board.innerHTML=state.notes.map((n,i)=>`<article class="sticky"><textarea data-note="${i}">${escapeHtml(n)}</textarea><footer><span>Sticky note</span><button data-del="${i}">Delete</button></footer></article>`).join(''); board.querySelectorAll('textarea').forEach(t=>t.addEventListener('input',()=>{state.notes[+t.dataset.note]=t.value;save();})); board.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.notes.splice(+b.dataset.del,1);save();renderNotes();});}
  const addNote=document.getElementById('addNote'); if(addNote)addNote.onclick=()=>{state.notes.unshift('New project note...');save();renderNotes();};
  document.querySelectorAll('.add-task').forEach(b=>b.onclick=()=>{const d=document.createElement('div');d.className='task';d.contentEditable='true';d.innerHTML='<b>New task</b><p>Add details...</p>';b.before(d);});
  const canvas=document.getElementById('board'); if(canvas){const ctx=canvas.getContext('2d');let tool='pen',drawing=false,start=null,img=null;function init(){ctx.fillStyle='#0b0f15';ctx.fillRect(0,0,canvas.width,canvas.height);if(state.board){const i=new Image();i.onload=()=>ctx.drawImage(i,0,0);i.src=state.board;}}init();document.querySelectorAll('.tool').forEach(btn=>btn.onclick=()=>{tool=btn.dataset.tool;document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x===btn));});canvas.addEventListener('mousedown',e=>{drawing=true;start=pos(e); if(tool==='text'){const text=prompt('Add text'); if(text){ctx.font='28px Arial';ctx.fillStyle='#ffb000';ctx.fillText(text,start.x,start.y);state.board=canvas.toDataURL();save();} drawing=false;}});canvas.addEventListener('mousemove',e=>{if(!drawing||tool!=='pen')return;const p=pos(e);ctx.strokeStyle='#ffb000';ctx.lineWidth=5;ctx.lineCap='round';ctx.lineTo(p.x,p.y);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x,p.y);});canvas.addEventListener('mouseup',e=>{if(!drawing)return;const end=pos(e);ctx.strokeStyle='#ffb000';ctx.lineWidth=5;ctx.fillStyle='rgba(255,176,0,.12)';if(tool==='line'){ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke();}if(tool==='rect'){ctx.strokeRect(start.x,start.y,end.x-start.x,end.y-start.y);}if(tool==='circle'){ctx.beginPath();ctx.arc(start.x,start.y,Math.hypot(end.x-start.x,end.y-start.y),0,Math.PI*2);ctx.stroke();}ctx.beginPath();drawing=false;state.board=canvas.toDataURL();save();});canvas.addEventListener('mouseleave',()=>{drawing=false;ctx.beginPath();});document.getElementById('clearBoard').onclick=()=>{state.board=null;init();save();};document.getElementById('saveBoard').onclick=()=>{state.board=canvas.toDataURL();save();alert('Whiteboard saved to this project in local storage.');};document.getElementById('imageUpload').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{img=new Image();img.onload=()=>{ctx.fillStyle='#0b0f15';ctx.fillRect(0,0,canvas.width,canvas.height);const scale=Math.min(canvas.width/img.width,canvas.height/img.height);const w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(canvas.width-w)/2,(canvas.height-h)/2,w,h);state.board=canvas.toDataURL();save();};img.src=reader.result;};reader.readAsDataURL(file);});function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}}
  function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
  renderRooms();renderMessages();renderNotes();save();
})();
